//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAP_BaiTap_01_World_Client.WorldServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Country : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContinentField;
        
        private int PopulationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Continent {
            get {
                return this.ContinentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContinentField, value) != true)) {
                    this.ContinentField = value;
                    this.RaisePropertyChanged("Continent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Population {
            get {
                return this.PopulationField;
            }
            set {
                if ((this.PopulationField.Equals(value) != true)) {
                    this.PopulationField = value;
                    this.RaisePropertyChanged("Population");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class City : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictField;
        
        private int PopulationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string District {
            get {
                return this.DistrictField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictField, value) != true)) {
                    this.DistrictField = value;
                    this.RaisePropertyChanged("District");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Population {
            get {
                return this.PopulationField;
            }
            set {
                if ((this.PopulationField.Equals(value) != true)) {
                    this.PopulationField = value;
                    this.RaisePropertyChanged("Population");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WorldServiceReference.WorldServiceSoap")]
    public interface WorldServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllCountriesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCountries", ReplyAction="*")]
        SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllCountriesResponse GetAllCountries(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllCountriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCountries", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllCountriesResponse> GetAllCountriesAsync(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllCountriesRequest request);
        
        // CODEGEN: Generating message contract since element name countryCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountryByCode", ReplyAction="*")]
        SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCountryByCodeResponse GetCountryByCode(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCountryByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountryByCode", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCountryByCodeResponse> GetCountryByCodeAsync(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCountryByCodeRequest request);
        
        // CODEGEN: Generating message contract since element name countryCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCitiesByCountry", ReplyAction="*")]
        SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCitiesByCountryResponse GetCitiesByCountry(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCitiesByCountryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCitiesByCountry", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCitiesByCountryResponse> GetCitiesByCountryAsync(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCitiesByCountryRequest request);
        
        // CODEGEN: Generating message contract since element name cityName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCityByName", ReplyAction="*")]
        SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCityByNameResponse GetCityByName(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCityByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCityByName", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCityByNameResponse> GetCityByNameAsync(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCityByNameRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllContinentsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllContinents", ReplyAction="*")]
        SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllContinentsResponse GetAllContinents(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllContinentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllContinents", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllContinentsResponse> GetAllContinentsAsync(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllContinentsRequest request);
        
        // CODEGEN: Generating message contract since element name continent from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalPopulationByContinent", ReplyAction="*")]
        SOAP_BaiTap_01_World_Client.WorldServiceReference.GetTotalPopulationByContinentResponse GetTotalPopulationByContinent(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetTotalPopulationByContinentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalPopulationByContinent", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAP_BaiTap_01_World_Client.WorldServiceReference.GetTotalPopulationByContinentResponse> GetTotalPopulationByContinentAsync(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetTotalPopulationByContinentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCountriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCountries", Namespace="http://tempuri.org/", Order=0)]
        public SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllCountriesRequestBody Body;
        
        public GetAllCountriesRequest() {
        }
        
        public GetAllCountriesRequest(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllCountriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCountriesRequestBody {
        
        public GetAllCountriesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCountriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCountriesResponse", Namespace="http://tempuri.org/", Order=0)]
        public SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllCountriesResponseBody Body;
        
        public GetAllCountriesResponse() {
        }
        
        public GetAllCountriesResponse(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllCountriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCountriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SOAP_BaiTap_01_World_Client.WorldServiceReference.Country[] GetAllCountriesResult;
        
        public GetAllCountriesResponseBody() {
        }
        
        public GetAllCountriesResponseBody(SOAP_BaiTap_01_World_Client.WorldServiceReference.Country[] GetAllCountriesResult) {
            this.GetAllCountriesResult = GetAllCountriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountryByCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountryByCode", Namespace="http://tempuri.org/", Order=0)]
        public SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCountryByCodeRequestBody Body;
        
        public GetCountryByCodeRequest() {
        }
        
        public GetCountryByCodeRequest(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCountryByCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountryByCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string countryCode;
        
        public GetCountryByCodeRequestBody() {
        }
        
        public GetCountryByCodeRequestBody(string countryCode) {
            this.countryCode = countryCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountryByCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountryByCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCountryByCodeResponseBody Body;
        
        public GetCountryByCodeResponse() {
        }
        
        public GetCountryByCodeResponse(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCountryByCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountryByCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SOAP_BaiTap_01_World_Client.WorldServiceReference.Country GetCountryByCodeResult;
        
        public GetCountryByCodeResponseBody() {
        }
        
        public GetCountryByCodeResponseBody(SOAP_BaiTap_01_World_Client.WorldServiceReference.Country GetCountryByCodeResult) {
            this.GetCountryByCodeResult = GetCountryByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCitiesByCountryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCitiesByCountry", Namespace="http://tempuri.org/", Order=0)]
        public SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCitiesByCountryRequestBody Body;
        
        public GetCitiesByCountryRequest() {
        }
        
        public GetCitiesByCountryRequest(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCitiesByCountryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCitiesByCountryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string countryCode;
        
        public GetCitiesByCountryRequestBody() {
        }
        
        public GetCitiesByCountryRequestBody(string countryCode) {
            this.countryCode = countryCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCitiesByCountryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCitiesByCountryResponse", Namespace="http://tempuri.org/", Order=0)]
        public SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCitiesByCountryResponseBody Body;
        
        public GetCitiesByCountryResponse() {
        }
        
        public GetCitiesByCountryResponse(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCitiesByCountryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCitiesByCountryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SOAP_BaiTap_01_World_Client.WorldServiceReference.City[] GetCitiesByCountryResult;
        
        public GetCitiesByCountryResponseBody() {
        }
        
        public GetCitiesByCountryResponseBody(SOAP_BaiTap_01_World_Client.WorldServiceReference.City[] GetCitiesByCountryResult) {
            this.GetCitiesByCountryResult = GetCitiesByCountryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCityByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCityByName", Namespace="http://tempuri.org/", Order=0)]
        public SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCityByNameRequestBody Body;
        
        public GetCityByNameRequest() {
        }
        
        public GetCityByNameRequest(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCityByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCityByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cityName;
        
        public GetCityByNameRequestBody() {
        }
        
        public GetCityByNameRequestBody(string cityName) {
            this.cityName = cityName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCityByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCityByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCityByNameResponseBody Body;
        
        public GetCityByNameResponse() {
        }
        
        public GetCityByNameResponse(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCityByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCityByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SOAP_BaiTap_01_World_Client.WorldServiceReference.City GetCityByNameResult;
        
        public GetCityByNameResponseBody() {
        }
        
        public GetCityByNameResponseBody(SOAP_BaiTap_01_World_Client.WorldServiceReference.City GetCityByNameResult) {
            this.GetCityByNameResult = GetCityByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllContinentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllContinents", Namespace="http://tempuri.org/", Order=0)]
        public SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllContinentsRequestBody Body;
        
        public GetAllContinentsRequest() {
        }
        
        public GetAllContinentsRequest(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllContinentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllContinentsRequestBody {
        
        public GetAllContinentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllContinentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllContinentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllContinentsResponseBody Body;
        
        public GetAllContinentsResponse() {
        }
        
        public GetAllContinentsResponse(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllContinentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllContinentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SOAP_BaiTap_01_World_Client.WorldServiceReference.ArrayOfString GetAllContinentsResult;
        
        public GetAllContinentsResponseBody() {
        }
        
        public GetAllContinentsResponseBody(SOAP_BaiTap_01_World_Client.WorldServiceReference.ArrayOfString GetAllContinentsResult) {
            this.GetAllContinentsResult = GetAllContinentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTotalPopulationByContinentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTotalPopulationByContinent", Namespace="http://tempuri.org/", Order=0)]
        public SOAP_BaiTap_01_World_Client.WorldServiceReference.GetTotalPopulationByContinentRequestBody Body;
        
        public GetTotalPopulationByContinentRequest() {
        }
        
        public GetTotalPopulationByContinentRequest(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetTotalPopulationByContinentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTotalPopulationByContinentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string continent;
        
        public GetTotalPopulationByContinentRequestBody() {
        }
        
        public GetTotalPopulationByContinentRequestBody(string continent) {
            this.continent = continent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTotalPopulationByContinentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTotalPopulationByContinentResponse", Namespace="http://tempuri.org/", Order=0)]
        public SOAP_BaiTap_01_World_Client.WorldServiceReference.GetTotalPopulationByContinentResponseBody Body;
        
        public GetTotalPopulationByContinentResponse() {
        }
        
        public GetTotalPopulationByContinentResponse(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetTotalPopulationByContinentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTotalPopulationByContinentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetTotalPopulationByContinentResult;
        
        public GetTotalPopulationByContinentResponseBody() {
        }
        
        public GetTotalPopulationByContinentResponseBody(int GetTotalPopulationByContinentResult) {
            this.GetTotalPopulationByContinentResult = GetTotalPopulationByContinentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WorldServiceSoapChannel : SOAP_BaiTap_01_World_Client.WorldServiceReference.WorldServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorldServiceSoapClient : System.ServiceModel.ClientBase<SOAP_BaiTap_01_World_Client.WorldServiceReference.WorldServiceSoap>, SOAP_BaiTap_01_World_Client.WorldServiceReference.WorldServiceSoap {
        
        public WorldServiceSoapClient() {
        }
        
        public WorldServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorldServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorldServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorldServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllCountriesResponse SOAP_BaiTap_01_World_Client.WorldServiceReference.WorldServiceSoap.GetAllCountries(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllCountriesRequest request) {
            return base.Channel.GetAllCountries(request);
        }
        
        public SOAP_BaiTap_01_World_Client.WorldServiceReference.Country[] GetAllCountries() {
            SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllCountriesRequest inValue = new SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllCountriesRequest();
            inValue.Body = new SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllCountriesRequestBody();
            SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllCountriesResponse retVal = ((SOAP_BaiTap_01_World_Client.WorldServiceReference.WorldServiceSoap)(this)).GetAllCountries(inValue);
            return retVal.Body.GetAllCountriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllCountriesResponse> SOAP_BaiTap_01_World_Client.WorldServiceReference.WorldServiceSoap.GetAllCountriesAsync(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllCountriesRequest request) {
            return base.Channel.GetAllCountriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllCountriesResponse> GetAllCountriesAsync() {
            SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllCountriesRequest inValue = new SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllCountriesRequest();
            inValue.Body = new SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllCountriesRequestBody();
            return ((SOAP_BaiTap_01_World_Client.WorldServiceReference.WorldServiceSoap)(this)).GetAllCountriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCountryByCodeResponse SOAP_BaiTap_01_World_Client.WorldServiceReference.WorldServiceSoap.GetCountryByCode(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCountryByCodeRequest request) {
            return base.Channel.GetCountryByCode(request);
        }
        
        public SOAP_BaiTap_01_World_Client.WorldServiceReference.Country GetCountryByCode(string countryCode) {
            SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCountryByCodeRequest inValue = new SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCountryByCodeRequest();
            inValue.Body = new SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCountryByCodeRequestBody();
            inValue.Body.countryCode = countryCode;
            SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCountryByCodeResponse retVal = ((SOAP_BaiTap_01_World_Client.WorldServiceReference.WorldServiceSoap)(this)).GetCountryByCode(inValue);
            return retVal.Body.GetCountryByCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCountryByCodeResponse> SOAP_BaiTap_01_World_Client.WorldServiceReference.WorldServiceSoap.GetCountryByCodeAsync(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCountryByCodeRequest request) {
            return base.Channel.GetCountryByCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCountryByCodeResponse> GetCountryByCodeAsync(string countryCode) {
            SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCountryByCodeRequest inValue = new SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCountryByCodeRequest();
            inValue.Body = new SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCountryByCodeRequestBody();
            inValue.Body.countryCode = countryCode;
            return ((SOAP_BaiTap_01_World_Client.WorldServiceReference.WorldServiceSoap)(this)).GetCountryByCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCitiesByCountryResponse SOAP_BaiTap_01_World_Client.WorldServiceReference.WorldServiceSoap.GetCitiesByCountry(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCitiesByCountryRequest request) {
            return base.Channel.GetCitiesByCountry(request);
        }
        
        public SOAP_BaiTap_01_World_Client.WorldServiceReference.City[] GetCitiesByCountry(string countryCode) {
            SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCitiesByCountryRequest inValue = new SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCitiesByCountryRequest();
            inValue.Body = new SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCitiesByCountryRequestBody();
            inValue.Body.countryCode = countryCode;
            SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCitiesByCountryResponse retVal = ((SOAP_BaiTap_01_World_Client.WorldServiceReference.WorldServiceSoap)(this)).GetCitiesByCountry(inValue);
            return retVal.Body.GetCitiesByCountryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCitiesByCountryResponse> SOAP_BaiTap_01_World_Client.WorldServiceReference.WorldServiceSoap.GetCitiesByCountryAsync(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCitiesByCountryRequest request) {
            return base.Channel.GetCitiesByCountryAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCitiesByCountryResponse> GetCitiesByCountryAsync(string countryCode) {
            SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCitiesByCountryRequest inValue = new SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCitiesByCountryRequest();
            inValue.Body = new SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCitiesByCountryRequestBody();
            inValue.Body.countryCode = countryCode;
            return ((SOAP_BaiTap_01_World_Client.WorldServiceReference.WorldServiceSoap)(this)).GetCitiesByCountryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCityByNameResponse SOAP_BaiTap_01_World_Client.WorldServiceReference.WorldServiceSoap.GetCityByName(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCityByNameRequest request) {
            return base.Channel.GetCityByName(request);
        }
        
        public SOAP_BaiTap_01_World_Client.WorldServiceReference.City GetCityByName(string cityName) {
            SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCityByNameRequest inValue = new SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCityByNameRequest();
            inValue.Body = new SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCityByNameRequestBody();
            inValue.Body.cityName = cityName;
            SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCityByNameResponse retVal = ((SOAP_BaiTap_01_World_Client.WorldServiceReference.WorldServiceSoap)(this)).GetCityByName(inValue);
            return retVal.Body.GetCityByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCityByNameResponse> SOAP_BaiTap_01_World_Client.WorldServiceReference.WorldServiceSoap.GetCityByNameAsync(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCityByNameRequest request) {
            return base.Channel.GetCityByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCityByNameResponse> GetCityByNameAsync(string cityName) {
            SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCityByNameRequest inValue = new SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCityByNameRequest();
            inValue.Body = new SOAP_BaiTap_01_World_Client.WorldServiceReference.GetCityByNameRequestBody();
            inValue.Body.cityName = cityName;
            return ((SOAP_BaiTap_01_World_Client.WorldServiceReference.WorldServiceSoap)(this)).GetCityByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllContinentsResponse SOAP_BaiTap_01_World_Client.WorldServiceReference.WorldServiceSoap.GetAllContinents(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllContinentsRequest request) {
            return base.Channel.GetAllContinents(request);
        }
        
        public SOAP_BaiTap_01_World_Client.WorldServiceReference.ArrayOfString GetAllContinents() {
            SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllContinentsRequest inValue = new SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllContinentsRequest();
            inValue.Body = new SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllContinentsRequestBody();
            SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllContinentsResponse retVal = ((SOAP_BaiTap_01_World_Client.WorldServiceReference.WorldServiceSoap)(this)).GetAllContinents(inValue);
            return retVal.Body.GetAllContinentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllContinentsResponse> SOAP_BaiTap_01_World_Client.WorldServiceReference.WorldServiceSoap.GetAllContinentsAsync(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllContinentsRequest request) {
            return base.Channel.GetAllContinentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllContinentsResponse> GetAllContinentsAsync() {
            SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllContinentsRequest inValue = new SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllContinentsRequest();
            inValue.Body = new SOAP_BaiTap_01_World_Client.WorldServiceReference.GetAllContinentsRequestBody();
            return ((SOAP_BaiTap_01_World_Client.WorldServiceReference.WorldServiceSoap)(this)).GetAllContinentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAP_BaiTap_01_World_Client.WorldServiceReference.GetTotalPopulationByContinentResponse SOAP_BaiTap_01_World_Client.WorldServiceReference.WorldServiceSoap.GetTotalPopulationByContinent(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetTotalPopulationByContinentRequest request) {
            return base.Channel.GetTotalPopulationByContinent(request);
        }
        
        public int GetTotalPopulationByContinent(string continent) {
            SOAP_BaiTap_01_World_Client.WorldServiceReference.GetTotalPopulationByContinentRequest inValue = new SOAP_BaiTap_01_World_Client.WorldServiceReference.GetTotalPopulationByContinentRequest();
            inValue.Body = new SOAP_BaiTap_01_World_Client.WorldServiceReference.GetTotalPopulationByContinentRequestBody();
            inValue.Body.continent = continent;
            SOAP_BaiTap_01_World_Client.WorldServiceReference.GetTotalPopulationByContinentResponse retVal = ((SOAP_BaiTap_01_World_Client.WorldServiceReference.WorldServiceSoap)(this)).GetTotalPopulationByContinent(inValue);
            return retVal.Body.GetTotalPopulationByContinentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAP_BaiTap_01_World_Client.WorldServiceReference.GetTotalPopulationByContinentResponse> SOAP_BaiTap_01_World_Client.WorldServiceReference.WorldServiceSoap.GetTotalPopulationByContinentAsync(SOAP_BaiTap_01_World_Client.WorldServiceReference.GetTotalPopulationByContinentRequest request) {
            return base.Channel.GetTotalPopulationByContinentAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAP_BaiTap_01_World_Client.WorldServiceReference.GetTotalPopulationByContinentResponse> GetTotalPopulationByContinentAsync(string continent) {
            SOAP_BaiTap_01_World_Client.WorldServiceReference.GetTotalPopulationByContinentRequest inValue = new SOAP_BaiTap_01_World_Client.WorldServiceReference.GetTotalPopulationByContinentRequest();
            inValue.Body = new SOAP_BaiTap_01_World_Client.WorldServiceReference.GetTotalPopulationByContinentRequestBody();
            inValue.Body.continent = continent;
            return ((SOAP_BaiTap_01_World_Client.WorldServiceReference.WorldServiceSoap)(this)).GetTotalPopulationByContinentAsync(inValue);
        }
    }
}
